# 服务器配置
server:
  port: 8888
  host: localhost

# 日志配置
logging:
  # HTTP请求日志中间件配置
  middleware:
    enabled: true # 是否启用HTTP请求日志中间件
    immediate: true # 是否立即记录日志
    format: SHORT # 日志格式: DEFAULT, SHORT, TINY, CUSTOM

# CORS配置
cors:
  enabled: true
  allowed_origins: "*" # 生产环境请设置具体域名
  allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed_headers:
    - Content-Type
    - Authorization
    - Access-Control-Allow-Method
    - Access-Control-Allow-Origin
    - Access-Control-Allow-Credentials
  allow_credentials: false # 是否允许发送凭证
  max_age: 86400 # 预检请求缓存时间（秒）

# 数据库配置
database:
  mysql:
    host: localhost
    port: 3306
    database: cte
    username: root
    password: root123
    max_pool_size: 5
    idle_timeout: 30000
    connect_timeout: 10000
    max_lifetime: 60000
    max_wait_queue_size: 100
  # redis:
  #   host: localhost
  #   port: 6379
  #   password:
  #   database: 0
  #   max_pool_size: 10

# 消息队列配置
mq:
  rabbitmq:
    enabled: true # 是否启用RabbitMQ
    host: 127.0.0.1
    port: 5672
    user: admin
    password: admin123
    virtualHost: /
    useSsl: false
    connectionTimeout: 60000 # 连接超时时间（毫秒）
    requestedHeartbeat: 60 # 心跳间隔（秒）
    handshakeTimeout: 10000 # 握手超时时间（毫秒）
    requestedChannelMax: 5 # 最大通道数
    networkRecoveryInterval: 5000 # 网络恢复间隔（毫秒）
    automaticRecovery: true # 是否自动恢复连接

    # 连接重试配置
    maxRetryAttempts: 10
    initialRetryDelay: 1000
    maxRetryDelay: 30000
    connectionCheckInterval: 10000
    # 连接池配置（用于发送消息）
    pool:
      initial_size: 5
      max_size: 20
      borrow_timeout_ms: 5000
      health_check_interval_ms: 30000
      enable_metrics: true
      idle_timeout_ms: 300000
      max_create_retries: 3

# 路由配置
router:
  # 请求体最大大小（字节），默认1MB
  max_request_body_size: 1048576
  # 扫描包路径
  base_package: "com.vertx.template"
  # 参数最大长度
  max_parameter_length: 1000
  # 是否启用参数校验
  # 参数校验开关配置
  # 功能说明：控制是否启用HTTP请求参数的长度校验和Bean Validation校验
  # 应用场景：
  #   1. 路径参数(PathParam)长度校验 - 防止过长的URL路径参数
  #   2. 查询参数(QueryParam)长度校验 - 防止过长的查询字符串
  #   3. 请求头(HeaderParam)长度校验 - 防止过长的HTTP头部值
  #   4. 请求体(RequestBody)的Bean Validation校验 - 使用@Valid注解时的数据校验
  # 校验规则：
  #   - 参数长度限制：由max_parameter_length配置项控制(默认1000字符)
  #   - Bean校验：使用JSR-303/JSR-380标准注解(@NotNull, @Size等)
  # 安全考虑：
  #   - 开启时可防止恶意超长参数攻击
  #   - 关闭时可提升性能但降低安全性
  # 默认值：true(推荐保持开启)
  enable_parameter_validation: true

# JWT配置
jwt:
  secret: "run6SCrvXZTQ3Mh4M9EZD3dSZYYp1se5"
  expire_seconds: 3600 # 1小时过期
  expire_offset_minutes: 5 # 过期时间偏移5分钟
  algorithm: "HS256"
